services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_cane_db
      MYSQL_USER: smart_cane_db
      MYSQL_PASSWORD: smart_cane_password
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      UPLOAD_LIMIT: 128M
    ports:
      - "8080:80"
    networks:
      - app-net

  middleware:
    build: ./middleware 
    container_name: middleware
    env_file:
      - .env
    expose:
      - "3000"
    # ports:
    #   - "3000:3000"
    networks:
      - app-net

  frontend:
    build: ./app
    container_name: frontend_app
    expose:
      - "80"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build: ./server
    container_name: backend_server
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "5000"
    depends_on:
      - mysql
    networks:
      - app-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    # depends_on:
    #   - frontend
    #   - backend
    #   - phpmyadmin
    networks:
      - app-net

volumes:
  mysql_data:

networks:
  app-net:
    driver: bridge
