services:
  graphhopper-import:
    image: israelhikingmap/graphhopper:latest
    container_name: graphhopper_import
    volumes:
      - ./maps:/data
    command: >
      --import
      -i /data/novaliches.osm.pbf
      -o /data/graph-cache
      -c /data/config.yml
    restart: "no"
    networks:
      - app-net

  graphhopper:
    image: israelhikingmap/graphhopper:latest
    container_name: graphhopper
    # expose:
    #   - "8989"
    ports:
      - "8989:8989"
    environment:
      - JAVA_OPTS=-Xmx2g
    volumes:
      - ./maps:/data
    restart: unless-stopped
    command: --config /data/config.yml
    depends_on:
      - graphhopper-import
    networks:
      - app-net
