services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # route-middleware:
  #   build: ./route-middleware
  #   container_name: route-middleware
  #   depends_on:
  #     - mosquitto
  #   environment:
  #     - MQTT_BROKER=mqtt://mosquitto:1883
  #     - GH_URL=http://graphhopper:8989/route

  # listener-middleware:
  #   build: ./listener-middleware
  #   container_name: listener-middleware
  #   depends_on:
  #     - mosquitto
  #   environment:
  #     - MQTT_BROKER=mqtt://mosquitto:1883
  #   ports:
  #     - "4000:4000"
  #     - "4001:4001"
  #   volumes:
  #     - ../../server.key:/etc/certs/server.key
  #     - ../../server.cert:/etc/certs/server.cert

  graphhopper-import:
    image: israelhikingmap/graphhopper:latest
    container_name: graphhopper_import
    volumes:
      - ./maps:/data
    command: >
      --import
      -i /data/novaliches.osm.pbf
      -o /data/graph-cache
      -c /data/config.yml
    restart: "no"

  # graphhopper:
  #   image: israelhikingmap/graphhopper:latest
  #   container_name: graphhopper
  #   ports:
  #     - "8989:8989"
  #   environment:
  #     - JAVA_OPTS=-Xmx2g
  #   volumes:
  #     - ./maps:/data
  #   restart: unless-stopped
  #   command: --config /data/config.yml
  #   depends_on:
  #     - graphhopper-import

  # frontend:
  #   build: ./app
  #   container_name: frontend_app
  #   ports:
  #     - "8080:80"
  #   restart: unless-stopped

  # backend:
  #   build: ./server
  #   container_name: backend_server
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
