FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install gunicorn

COPY . .

CMD ["gunicorn", "-w", "4", "--threads", "2", "-b", "0.0.0.0:5001", "run:app"]
